apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-h8zv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hiby-tenant/rhtap-demo-app/hacbs-test-project-h8zv@sha256:83716dd16f5a6d3727059627d5389d9c478d03477b05b46526c7f8040c49da98
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
