apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-h8zv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hiby-tenant/rhtap-demo-app/hacbs-test-project-h8zv@sha256:a340c1c8cb600139bdb98bd8f4a2ee421c98625875fef8f09438b32f74ed8a1c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
