apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-h8zv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hiby-tenant/rhtap-demo-app/hacbs-test-project-h8zv@sha256:f3468e1c63a639042cd4a259fda33220a78ebcf4a25cc1dbef0bc7202a8e5953
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
